### ISSUE TITLE
Does this work with Atom 1.24?

### ISSUE THREAD

**Issue by szeck87** [keplersj/atom-test-runner-jest#1]
Hi.  I've been trying to get this setup on my Atom package.  I keep receiving an error when I have this simple test:

```javascript
describe("My Delightful Package", () => {
  it("knows about all of Atom's loaded packages", () => {
    const packages = atom.packages.getLoadedPackages();
    expect(packages).toMatchSnapshot();
  })
})
```

ReferenceError: atom is not defined

**Comment by keplersj** [comment]
I'm afraid to say this is a very troubled, and experimental package at the moment.

If you wouldn't mind could you tell me how you ran the test to help confirm some of my theories? `atom --test .`? `apm test`?

**Comment by keplersj** [comment]
As well, I've updated the README to reflect the recommended configuration to use `jest-preset-atom`.

**Comment by Glavin001** [comment]
I think this will not work because Jest runs tests in a separate process and does not pass through `global`: https://github.com/facebook/jest/issues/4643
Looks like a custom test environment may be required? See https://github.com/facebook/jest/pull/4506

@keplersj Did you actually have this working at one point?

**Comment by keplersj** [comment]
@Glavin001 I did. That's the most infuriating thing. I had it working with a version of crystal-lang-tools/language-crystal.

A custom test environment is being used.

**Comment by szeck87** [comment]
@keplersj if I use that preset it just hangs, opens another Atom instance in the background like it usually does for tests, but just stays like that.

**Comment by keplersj** [comment]
@szeck87 Are you using the menu item in app, `atom --test .`, or `apm test`?

**Comment by szeck87** [comment]
atom --test .

**Comment by keplersj** [comment]
Able to replicate with version 0.1.3 of `jest-preset-atom` and version 0.1.3 atom-test-runner-jest.

**Comment by szeck87** [comment]
Yep, and without that in there it does run, just still doesn't recognize `atom`.

**Comment by keplersj** [comment]
I just updated `jest-preset-atom` so that the environment correctly passes down the Atom global. Does it work with `jest-preset-atom@0.1.4` and Jest config set to the following: 

```json
{
  "testEnvironment": "jest-preset-atom/environment"
}
```

**Comment by keplersj** [comment]
Defining just the `testEnvironment` like that doesn't do anything to handle non-ES6 transforms, so the test runner will not handle any specs or required files written in CoffeeScript or TypeScript like Atom will by default.

**Comment by keplersj** [comment]
I just updated `jest-preset-atom` to version 0.1.5. And the following Jest config is working with crystal-lang-tools/language-crystal locally:

```json
{
  "preset": "jest-preset-atom"
}
```

**Comment by szeck87** [comment]
Yea I'm getting somewhere.  Now getting errors on the waitsForPromise not being defined.  Thanks!

**Comment by keplersj** [comment]
`waitsForPromise` is exclusive to Jasmine. Feel free to async/await in Jest

**Comment by keplersj** [comment]
I'm gonna close this because we made progress on running. There are other issues. So, please continue to open issues. Thank you so much!

**Comment by Glavin001** [comment]
This is awesome news! Thank you very much for your help @keplersj !

**Comment by keplersj** [comment]
@Glavin001 Thank you! Right now the big issue is that I'm having trouble with this and CI. Working on atm.

**Comment by keplersj** [comment]
@Glavin001 @szeck87 I am happy to report that this preset is passing on CI now. https://travis-ci.org/crystal-lang-tools/language-crystal

**Comment by szeck87** [comment]
@keplersj thanks!  I'm having some trouble with the activatePackage timing out, even at 20 seconds.  Other than that it looks good.

**Comment by szeck87** [comment]
@keplersj I got it working.  Quick question, does it report test coverage at all?

**Comment by keplersj** [comment]
That's Jest's responsibility itself. I recommend seeing the documentation on enabling and configuring coverage in Jest.

**Comment by szeck87** [comment]
Correct, and I have it configured the way it should.  But it just shows

```
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                   |
----------|----------|----------|----------|----------|-------------------|
```

**Comment by keplersj** [comment]
The `language-crystal-actual` package doesn't need code coverage because it is not running any code. It's just checking how Atom tokenizes Crystal strings given the package's grammar CSON. If a coverage report for the CSON were generated code coverage would always be 100% regardless of tests written.

Jest can only create code coverage reports for files that Jest interacts with. It can't generate code coverage for tests that only activate the package through Atom, as it seems you're doing [here](https://github.com/szeck87/atom-beautify/commit/412ca9db6e4bcd7539a3fab5dde21e90bc2b58d5).
