### ISSUE TITLE
ReferenceError: atom is not defined

### ISSUE THREAD

**Issue by szeck87** [keplersj/atom-test-runner-jest#2]
I updated atom-test-runner-jest to 0.2.3 from 0.1.3.  When I run `atom --test spec`, it errors with:

> ReferenceError: atom is not defined

The console shows this error happening on two lines:  
https://github.com/szeck87/atom-beautify/blob/unibeautify/spec/atombeautify.spec.js#L4 
https://github.com/szeck87/atom-beautify/blob/unibeautify/spec/atombeautify.spec.js#L11.  0.1.3 did not have any errors.

**Comment by keplersj** [comment]
I just did some debugging on your project. I resolved the issue by moving the Jest config to `package.json` from `jest.config.js`. It looks to me that Jest was running your test suite the environment as set up by `jest-preset-atom` was not being configured.

**Comment by szeck87** [comment]
Is it an error here or should I open it in https://github.com/keplersj/jest-preset-atom?

**Comment by keplersj** [comment]
The bug is here
