### ISSUE TITLE
renderer process crash

### ISSUE THREAD

**Issue by alvarolorentedev** [keplersj/atom-test-runner-jest#3]
Hello @keplersj. first of all great initiative :) . 
I have tried to use the test runner with the preset but it crashes as you can see on the next bash snippet

```sh
atom --test .  
 RUNS  test/unit/lib/view-models/search-test.js
2018-08-09 07:54:21.869 Atom[7068:102528] Renderer process crashed, exiting
```
Any ideas if its related to the test runner? I have been testing my application manually and running manual testing and the package does not crash atom or jest in those cases.
 
If its worth it the repo I am working in is: https://github.com/kanekotic/playyoutube-atom

**Comment by stevenzeck** [comment]
@keplersj any ideas here?

**Comment by banacorn** [comment]
Facebook also have their version of ["jest-atom-runner"](https://github.com/facebookarchive/nuclide/tree/master/modules/jest-atom-runner).
It seems like they are using different processes for running and rendering the test or something.

**Comment by banacorn** [comment]
I'm gonna deep dive and try to fix this, any help would be appreciated.

**Comment by alvarolorentedev** [comment]
Staled
